// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/CircleCI-Public/circleci-cli"
	_ "github.com/gogo/protobuf/protoc-gen-gogo"
	_ "github.com/golang/mock/mockgen"
	_ "github.com/golangci/golangci-lint/cmd/golangci-lint"
	_ "github.com/hexdigest/gowrap"
	_ "github.com/lyft/protoc-gen-validate"
	_ "go.zenithar.org/protoc-gen-cobra"
	_ "gotest.tools/gotestsum"
)
