// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/grpc/v1/spotigraph/pb/spotigraph.proto

/*
	Package pb is a generated protocol buffer package.

	It is generated from these files:
		pkg/grpc/v1/spotigraph/pb/spotigraph.proto

	It has these top-level messages:
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import spotigraph_v1 "go.zenithar.org/spotigraph/pkg/protocol/v1/spotigraph"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	Create(ctx context.Context, in *spotigraph_v1.UserCreateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleUserRes, error)
	Get(ctx context.Context, in *spotigraph_v1.UserGetReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleUserRes, error)
	Update(ctx context.Context, in *spotigraph_v1.UserUpdateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleUserRes, error)
	Delete(ctx context.Context, in *spotigraph_v1.UserGetReq, opts ...grpc.CallOption) (*spotigraph_v1.EmptyRes, error)
	Search(ctx context.Context, in *spotigraph_v1.UserSearchReq, opts ...grpc.CallOption) (*spotigraph_v1.PaginatedUserRes, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Create(ctx context.Context, in *spotigraph_v1.UserCreateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleUserRes, error) {
	out := new(spotigraph_v1.SingleUserRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.User/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Get(ctx context.Context, in *spotigraph_v1.UserGetReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleUserRes, error) {
	out := new(spotigraph_v1.SingleUserRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.User/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Update(ctx context.Context, in *spotigraph_v1.UserUpdateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleUserRes, error) {
	out := new(spotigraph_v1.SingleUserRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.User/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Delete(ctx context.Context, in *spotigraph_v1.UserGetReq, opts ...grpc.CallOption) (*spotigraph_v1.EmptyRes, error) {
	out := new(spotigraph_v1.EmptyRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.User/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Search(ctx context.Context, in *spotigraph_v1.UserSearchReq, opts ...grpc.CallOption) (*spotigraph_v1.PaginatedUserRes, error) {
	out := new(spotigraph_v1.PaginatedUserRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.User/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	Create(context.Context, *spotigraph_v1.UserCreateReq) (*spotigraph_v1.SingleUserRes, error)
	Get(context.Context, *spotigraph_v1.UserGetReq) (*spotigraph_v1.SingleUserRes, error)
	Update(context.Context, *spotigraph_v1.UserUpdateReq) (*spotigraph_v1.SingleUserRes, error)
	Delete(context.Context, *spotigraph_v1.UserGetReq) (*spotigraph_v1.EmptyRes, error)
	Search(context.Context, *spotigraph_v1.UserSearchReq) (*spotigraph_v1.PaginatedUserRes, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.UserCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.User/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Create(ctx, req.(*spotigraph_v1.UserCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.UserGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.User/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Get(ctx, req.(*spotigraph_v1.UserGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.UserUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.User/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Update(ctx, req.(*spotigraph_v1.UserUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.UserGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.User/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Delete(ctx, req.(*spotigraph_v1.UserGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.UserSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.User/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Search(ctx, req.(*spotigraph_v1.UserSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.spotigraph.v1.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _User_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _User_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _User_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _User_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _User_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/v1/spotigraph/pb/spotigraph.proto",
}

// Client API for Squad service

type SquadClient interface {
	Create(ctx context.Context, in *spotigraph_v1.SquadCreateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleSquadRes, error)
	Get(ctx context.Context, in *spotigraph_v1.SquadGetReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleSquadRes, error)
	Update(ctx context.Context, in *spotigraph_v1.SquadUpdateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleSquadRes, error)
	Delete(ctx context.Context, in *spotigraph_v1.SquadGetReq, opts ...grpc.CallOption) (*spotigraph_v1.EmptyRes, error)
	Search(ctx context.Context, in *spotigraph_v1.SquadSearchReq, opts ...grpc.CallOption) (*spotigraph_v1.PaginatedSquadRes, error)
}

type squadClient struct {
	cc *grpc.ClientConn
}

func NewSquadClient(cc *grpc.ClientConn) SquadClient {
	return &squadClient{cc}
}

func (c *squadClient) Create(ctx context.Context, in *spotigraph_v1.SquadCreateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleSquadRes, error) {
	out := new(spotigraph_v1.SingleSquadRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Squad/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squadClient) Get(ctx context.Context, in *spotigraph_v1.SquadGetReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleSquadRes, error) {
	out := new(spotigraph_v1.SingleSquadRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Squad/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squadClient) Update(ctx context.Context, in *spotigraph_v1.SquadUpdateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleSquadRes, error) {
	out := new(spotigraph_v1.SingleSquadRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Squad/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squadClient) Delete(ctx context.Context, in *spotigraph_v1.SquadGetReq, opts ...grpc.CallOption) (*spotigraph_v1.EmptyRes, error) {
	out := new(spotigraph_v1.EmptyRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Squad/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squadClient) Search(ctx context.Context, in *spotigraph_v1.SquadSearchReq, opts ...grpc.CallOption) (*spotigraph_v1.PaginatedSquadRes, error) {
	out := new(spotigraph_v1.PaginatedSquadRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Squad/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Squad service

type SquadServer interface {
	Create(context.Context, *spotigraph_v1.SquadCreateReq) (*spotigraph_v1.SingleSquadRes, error)
	Get(context.Context, *spotigraph_v1.SquadGetReq) (*spotigraph_v1.SingleSquadRes, error)
	Update(context.Context, *spotigraph_v1.SquadUpdateReq) (*spotigraph_v1.SingleSquadRes, error)
	Delete(context.Context, *spotigraph_v1.SquadGetReq) (*spotigraph_v1.EmptyRes, error)
	Search(context.Context, *spotigraph_v1.SquadSearchReq) (*spotigraph_v1.PaginatedSquadRes, error)
}

func RegisterSquadServer(s *grpc.Server, srv SquadServer) {
	s.RegisterService(&_Squad_serviceDesc, srv)
}

func _Squad_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.SquadCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquadServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Squad/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquadServer).Create(ctx, req.(*spotigraph_v1.SquadCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Squad_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.SquadGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquadServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Squad/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquadServer).Get(ctx, req.(*spotigraph_v1.SquadGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Squad_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.SquadUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquadServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Squad/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquadServer).Update(ctx, req.(*spotigraph_v1.SquadUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Squad_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.SquadGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquadServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Squad/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquadServer).Delete(ctx, req.(*spotigraph_v1.SquadGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Squad_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.SquadSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquadServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Squad/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquadServer).Search(ctx, req.(*spotigraph_v1.SquadSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Squad_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.spotigraph.v1.Squad",
	HandlerType: (*SquadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Squad_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Squad_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Squad_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Squad_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Squad_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/v1/spotigraph/pb/spotigraph.proto",
}

// Client API for Chapter service

type ChapterClient interface {
	Create(ctx context.Context, in *spotigraph_v1.ChapterCreateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleChapterRes, error)
	Get(ctx context.Context, in *spotigraph_v1.ChapterGetReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleChapterRes, error)
	Update(ctx context.Context, in *spotigraph_v1.ChapterUpdateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleChapterRes, error)
	Delete(ctx context.Context, in *spotigraph_v1.ChapterGetReq, opts ...grpc.CallOption) (*spotigraph_v1.EmptyRes, error)
	Search(ctx context.Context, in *spotigraph_v1.ChapterSearchReq, opts ...grpc.CallOption) (*spotigraph_v1.PaginatedChapterRes, error)
}

type chapterClient struct {
	cc *grpc.ClientConn
}

func NewChapterClient(cc *grpc.ClientConn) ChapterClient {
	return &chapterClient{cc}
}

func (c *chapterClient) Create(ctx context.Context, in *spotigraph_v1.ChapterCreateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleChapterRes, error) {
	out := new(spotigraph_v1.SingleChapterRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Chapter/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) Get(ctx context.Context, in *spotigraph_v1.ChapterGetReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleChapterRes, error) {
	out := new(spotigraph_v1.SingleChapterRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Chapter/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) Update(ctx context.Context, in *spotigraph_v1.ChapterUpdateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleChapterRes, error) {
	out := new(spotigraph_v1.SingleChapterRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Chapter/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) Delete(ctx context.Context, in *spotigraph_v1.ChapterGetReq, opts ...grpc.CallOption) (*spotigraph_v1.EmptyRes, error) {
	out := new(spotigraph_v1.EmptyRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Chapter/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterClient) Search(ctx context.Context, in *spotigraph_v1.ChapterSearchReq, opts ...grpc.CallOption) (*spotigraph_v1.PaginatedChapterRes, error) {
	out := new(spotigraph_v1.PaginatedChapterRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Chapter/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Chapter service

type ChapterServer interface {
	Create(context.Context, *spotigraph_v1.ChapterCreateReq) (*spotigraph_v1.SingleChapterRes, error)
	Get(context.Context, *spotigraph_v1.ChapterGetReq) (*spotigraph_v1.SingleChapterRes, error)
	Update(context.Context, *spotigraph_v1.ChapterUpdateReq) (*spotigraph_v1.SingleChapterRes, error)
	Delete(context.Context, *spotigraph_v1.ChapterGetReq) (*spotigraph_v1.EmptyRes, error)
	Search(context.Context, *spotigraph_v1.ChapterSearchReq) (*spotigraph_v1.PaginatedChapterRes, error)
}

func RegisterChapterServer(s *grpc.Server, srv ChapterServer) {
	s.RegisterService(&_Chapter_serviceDesc, srv)
}

func _Chapter_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.ChapterCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Chapter/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).Create(ctx, req.(*spotigraph_v1.ChapterCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.ChapterGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Chapter/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).Get(ctx, req.(*spotigraph_v1.ChapterGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.ChapterUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Chapter/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).Update(ctx, req.(*spotigraph_v1.ChapterUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.ChapterGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Chapter/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).Delete(ctx, req.(*spotigraph_v1.ChapterGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chapter_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.ChapterSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Chapter/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServer).Search(ctx, req.(*spotigraph_v1.ChapterSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chapter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.spotigraph.v1.Chapter",
	HandlerType: (*ChapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Chapter_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Chapter_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Chapter_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Chapter_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Chapter_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/v1/spotigraph/pb/spotigraph.proto",
}

// Client API for Guild service

type GuildClient interface {
	Create(ctx context.Context, in *spotigraph_v1.GuildCreateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleGuildRes, error)
	Get(ctx context.Context, in *spotigraph_v1.GuildGetReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleGuildRes, error)
	Update(ctx context.Context, in *spotigraph_v1.GuildUpdateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleGuildRes, error)
	Delete(ctx context.Context, in *spotigraph_v1.GuildGetReq, opts ...grpc.CallOption) (*spotigraph_v1.EmptyRes, error)
	Search(ctx context.Context, in *spotigraph_v1.GuildSearchReq, opts ...grpc.CallOption) (*spotigraph_v1.PaginatedGuildRes, error)
}

type guildClient struct {
	cc *grpc.ClientConn
}

func NewGuildClient(cc *grpc.ClientConn) GuildClient {
	return &guildClient{cc}
}

func (c *guildClient) Create(ctx context.Context, in *spotigraph_v1.GuildCreateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleGuildRes, error) {
	out := new(spotigraph_v1.SingleGuildRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Guild/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) Get(ctx context.Context, in *spotigraph_v1.GuildGetReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleGuildRes, error) {
	out := new(spotigraph_v1.SingleGuildRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Guild/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) Update(ctx context.Context, in *spotigraph_v1.GuildUpdateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleGuildRes, error) {
	out := new(spotigraph_v1.SingleGuildRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Guild/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) Delete(ctx context.Context, in *spotigraph_v1.GuildGetReq, opts ...grpc.CallOption) (*spotigraph_v1.EmptyRes, error) {
	out := new(spotigraph_v1.EmptyRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Guild/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildClient) Search(ctx context.Context, in *spotigraph_v1.GuildSearchReq, opts ...grpc.CallOption) (*spotigraph_v1.PaginatedGuildRes, error) {
	out := new(spotigraph_v1.PaginatedGuildRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Guild/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Guild service

type GuildServer interface {
	Create(context.Context, *spotigraph_v1.GuildCreateReq) (*spotigraph_v1.SingleGuildRes, error)
	Get(context.Context, *spotigraph_v1.GuildGetReq) (*spotigraph_v1.SingleGuildRes, error)
	Update(context.Context, *spotigraph_v1.GuildUpdateReq) (*spotigraph_v1.SingleGuildRes, error)
	Delete(context.Context, *spotigraph_v1.GuildGetReq) (*spotigraph_v1.EmptyRes, error)
	Search(context.Context, *spotigraph_v1.GuildSearchReq) (*spotigraph_v1.PaginatedGuildRes, error)
}

func RegisterGuildServer(s *grpc.Server, srv GuildServer) {
	s.RegisterService(&_Guild_serviceDesc, srv)
}

func _Guild_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.GuildCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Guild/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).Create(ctx, req.(*spotigraph_v1.GuildCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.GuildGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Guild/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).Get(ctx, req.(*spotigraph_v1.GuildGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.GuildUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Guild/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).Update(ctx, req.(*spotigraph_v1.GuildUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.GuildGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Guild/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).Delete(ctx, req.(*spotigraph_v1.GuildGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guild_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.GuildSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Guild/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).Search(ctx, req.(*spotigraph_v1.GuildSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Guild_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.spotigraph.v1.Guild",
	HandlerType: (*GuildServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Guild_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Guild_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Guild_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Guild_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Guild_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/v1/spotigraph/pb/spotigraph.proto",
}

// Client API for Tribe service

type TribeClient interface {
	Create(ctx context.Context, in *spotigraph_v1.TribeCreateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleTribeRes, error)
	Get(ctx context.Context, in *spotigraph_v1.TribeGetReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleTribeRes, error)
	Update(ctx context.Context, in *spotigraph_v1.TribeUpdateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleTribeRes, error)
	Delete(ctx context.Context, in *spotigraph_v1.TribeGetReq, opts ...grpc.CallOption) (*spotigraph_v1.EmptyRes, error)
	Search(ctx context.Context, in *spotigraph_v1.TribeSearchReq, opts ...grpc.CallOption) (*spotigraph_v1.PaginatedTribeRes, error)
}

type tribeClient struct {
	cc *grpc.ClientConn
}

func NewTribeClient(cc *grpc.ClientConn) TribeClient {
	return &tribeClient{cc}
}

func (c *tribeClient) Create(ctx context.Context, in *spotigraph_v1.TribeCreateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleTribeRes, error) {
	out := new(spotigraph_v1.SingleTribeRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Tribe/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tribeClient) Get(ctx context.Context, in *spotigraph_v1.TribeGetReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleTribeRes, error) {
	out := new(spotigraph_v1.SingleTribeRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Tribe/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tribeClient) Update(ctx context.Context, in *spotigraph_v1.TribeUpdateReq, opts ...grpc.CallOption) (*spotigraph_v1.SingleTribeRes, error) {
	out := new(spotigraph_v1.SingleTribeRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Tribe/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tribeClient) Delete(ctx context.Context, in *spotigraph_v1.TribeGetReq, opts ...grpc.CallOption) (*spotigraph_v1.EmptyRes, error) {
	out := new(spotigraph_v1.EmptyRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Tribe/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tribeClient) Search(ctx context.Context, in *spotigraph_v1.TribeSearchReq, opts ...grpc.CallOption) (*spotigraph_v1.PaginatedTribeRes, error) {
	out := new(spotigraph_v1.PaginatedTribeRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Tribe/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tribe service

type TribeServer interface {
	Create(context.Context, *spotigraph_v1.TribeCreateReq) (*spotigraph_v1.SingleTribeRes, error)
	Get(context.Context, *spotigraph_v1.TribeGetReq) (*spotigraph_v1.SingleTribeRes, error)
	Update(context.Context, *spotigraph_v1.TribeUpdateReq) (*spotigraph_v1.SingleTribeRes, error)
	Delete(context.Context, *spotigraph_v1.TribeGetReq) (*spotigraph_v1.EmptyRes, error)
	Search(context.Context, *spotigraph_v1.TribeSearchReq) (*spotigraph_v1.PaginatedTribeRes, error)
}

func RegisterTribeServer(s *grpc.Server, srv TribeServer) {
	s.RegisterService(&_Tribe_serviceDesc, srv)
}

func _Tribe_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.TribeCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TribeServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Tribe/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TribeServer).Create(ctx, req.(*spotigraph_v1.TribeCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tribe_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.TribeGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TribeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Tribe/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TribeServer).Get(ctx, req.(*spotigraph_v1.TribeGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tribe_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.TribeUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TribeServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Tribe/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TribeServer).Update(ctx, req.(*spotigraph_v1.TribeUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tribe_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.TribeGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TribeServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Tribe/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TribeServer).Delete(ctx, req.(*spotigraph_v1.TribeGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tribe_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.TribeSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TribeServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Tribe/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TribeServer).Search(ctx, req.(*spotigraph_v1.TribeSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tribe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.spotigraph.v1.Tribe",
	HandlerType: (*TribeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Tribe_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Tribe_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Tribe_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Tribe_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Tribe_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/v1/spotigraph/pb/spotigraph.proto",
}

// Client API for Graph service

type GraphClient interface {
	Expand(ctx context.Context, in *spotigraph_v1.NodeInfoReq, opts ...grpc.CallOption) (*spotigraph_v1.GraphRes, error)
}

type graphClient struct {
	cc *grpc.ClientConn
}

func NewGraphClient(cc *grpc.ClientConn) GraphClient {
	return &graphClient{cc}
}

func (c *graphClient) Expand(ctx context.Context, in *spotigraph_v1.NodeInfoReq, opts ...grpc.CallOption) (*spotigraph_v1.GraphRes, error) {
	out := new(spotigraph_v1.GraphRes)
	err := grpc.Invoke(ctx, "/grpc.spotigraph.v1.Graph/Expand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Graph service

type GraphServer interface {
	Expand(context.Context, *spotigraph_v1.NodeInfoReq) (*spotigraph_v1.GraphRes, error)
}

func RegisterGraphServer(s *grpc.Server, srv GraphServer) {
	s.RegisterService(&_Graph_serviceDesc, srv)
}

func _Graph_Expand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spotigraph_v1.NodeInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServer).Expand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.spotigraph.v1.Graph/Expand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServer).Expand(ctx, req.(*spotigraph_v1.NodeInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Graph_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.spotigraph.v1.Graph",
	HandlerType: (*GraphServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Expand",
			Handler:    _Graph_Expand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/v1/spotigraph/pb/spotigraph.proto",
}

func init() {
	proto.RegisterFile("pkg/grpc/v1/spotigraph/pb/spotigraph.proto", fileDescriptorSpotigraph)
}

var fileDescriptorSpotigraph = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x86, 0x45, 0xa0, 0x06, 0xed, 0x71, 0x2f, 0xa8, 0x51, 0xab, 0x56, 0x1c, 0x41, 0x72, 0xd4,
	0x70, 0xe5, 0x4b, 0x6d, 0x1a, 0x2b, 0x95, 0x8a, 0xa2, 0x84, 0x5e, 0xb8, 0x6d, 0xe2, 0xc1, 0xb1,
	0x30, 0xde, 0xed, 0x7a, 0x5b, 0x01, 0xff, 0x94, 0x33, 0x3f, 0x82, 0x2b, 0xda, 0xb1, 0xb3, 0x0e,
	0xcb, 0x7e, 0x54, 0x39, 0xa6, 0xef, 0xcc, 0xab, 0x67, 0x9f, 0x8e, 0x64, 0xf2, 0x52, 0x7c, 0x2d,
	0x46, 0x85, 0x14, 0xeb, 0xd1, 0xfd, 0xd9, 0xa8, 0x11, 0x5c, 0x95, 0x85, 0x64, 0x62, 0x33, 0x12,
	0xab, 0x9d, 0x5f, 0xa9, 0x90, 0x5c, 0x71, 0x4a, 0xf5, 0x5c, 0xba, 0xf3, 0xe7, 0xfb, 0xb3, 0xe1,
	0x2b, 0xbd, 0x8f, 0xf1, 0x9a, 0x57, 0x56, 0x87, 0x5d, 0x30, 0xfe, 0x35, 0x20, 0x4f, 0x6e, 0x1a,
	0x90, 0x74, 0x42, 0x92, 0x0b, 0x09, 0x4c, 0x01, 0x3d, 0xfa, 0xb7, 0x2f, 0xd5, 0x71, 0x1b, 0x2d,
	0xe0, 0x76, 0x68, 0xa7, 0xcb, 0xb2, 0x2e, 0x2a, 0xd0, 0x33, 0x0b, 0x68, 0xe8, 0x3b, 0xf2, 0x38,
	0x03, 0x45, 0x0f, 0x1d, 0x15, 0x19, 0xa8, 0xf8, 0xfe, 0x84, 0x24, 0x37, 0x22, 0xf7, 0x51, 0xb4,
	0x51, 0xbc, 0xe5, 0x0d, 0x49, 0x26, 0x50, 0x81, 0x82, 0x10, 0xc8, 0x73, 0x2b, 0xba, 0xfc, 0x26,
	0xd4, 0x0f, 0xbd, 0x9d, 0x91, 0x64, 0x09, 0x4c, 0xae, 0x37, 0x4e, 0x86, 0x36, 0xd2, 0x05, 0x27,
	0x56, 0x3a, 0x67, 0x45, 0x59, 0x33, 0x05, 0x79, 0x87, 0x31, 0xfe, 0x3d, 0x20, 0x07, 0xcb, 0xdb,
	0x3b, 0x96, 0xd3, 0xa9, 0x91, 0x7b, 0x6c, 0x83, 0xeb, 0xbc, 0xb7, 0x7b, 0xec, 0x7c, 0x17, 0x0e,
	0x69, 0xb4, 0x0f, 0xad, 0xde, 0xa1, 0xab, 0xa4, 0x7b, 0x56, 0xa4, 0x61, 0x6a, 0x04, 0x3b, 0x49,
	0x7a, 0xc3, 0x91, 0x9e, 0xb7, 0x46, 0x71, 0x08, 0xc6, 0xeb, 0x78, 0x66, 0x1c, 0x3b, 0x31, 0x7a,
	0xc9, 0xa7, 0x3e, 0xc9, 0x5b, 0x92, 0xf1, 0x9f, 0x01, 0x79, 0x7a, 0xb1, 0x61, 0x42, 0x81, 0xa4,
	0x57, 0xc6, 0xb3, 0xfd, 0xcf, 0xe9, 0x26, 0x7a, 0xd3, 0x27, 0xce, 0xf7, 0x75, 0x63, 0xed, 0x29,
	0xa2, 0xeb, 0x23, 0x77, 0x51, 0xf7, 0xc0, 0x68, 0xcb, 0x95, 0xf1, 0xed, 0x21, 0xea, 0x8d, 0x47,
	0xbb, 0xde, 0x1b, 0xe7, 0x61, 0x28, 0xaf, 0xf5, 0x6b, 0x63, 0xdd, 0x03, 0xd3, 0x7b, 0x7f, 0xe1,
	0xf3, 0xde, 0xf3, 0xe0, 0x7d, 0x67, 0x77, 0x65, 0x15, 0xba, 0x6f, 0xcc, 0x63, 0xf7, 0x8d, 0x43,
	0x81, 0xfb, 0xc6, 0x3c, 0x78, 0xdf, 0xa6, 0xc1, 0x7f, 0xdf, 0x38, 0x12, 0xbb, 0x6f, 0xd3, 0xe3,
	0xbf, 0xef, 0x5d, 0x98, 0x3d, 0xee, 0x1b, 0xd7, 0x1f, 0x70, 0xdf, 0x5b, 0x12, 0xb4, 0xfc, 0x49,
	0x96, 0x2b, 0x08, 0x58, 0xc6, 0x3c, 0x66, 0x19, 0x87, 0x02, 0x96, 0x31, 0x0f, 0x5a, 0x36, 0x0d,
	0x7e, 0xcb, 0x38, 0x12, 0xb3, 0x6c, 0x7a, 0xfc, 0x96, 0x77, 0x61, 0xf6, 0xb0, 0x8c, 0xeb, 0x0f,
	0xb0, 0xbc, 0x25, 0x19, 0x4f, 0xc9, 0x41, 0xa6, 0x53, 0x8d, 0x74, 0xf9, 0x5d, 0xb0, 0x3a, 0xff,
	0x0f, 0xe9, 0x23, 0xcf, 0x61, 0x56, 0x7f, 0xe1, 0x2e, 0x24, 0xdc, 0x5d, 0x40, 0x73, 0x3e, 0x23,
	0xa7, 0x5c, 0x16, 0xe9, 0x4f, 0xa8, 0x4b, 0xb5, 0x61, 0x32, 0xb5, 0x3f, 0xb8, 0x6b, 0x5e, 0x9d,
	0x3f, 0xbb, 0x6e, 0x8a, 0xb9, 0xfe, 0x31, 0x7f, 0xf4, 0xf9, 0xd0, 0xfb, 0xb1, 0x5f, 0x25, 0xb8,
	0xf0, 0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x54, 0xce, 0xd6, 0x10, 0x08, 0x00, 0x00,
}
