// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package postgresql

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("./migrations", "1.sql", "\"H4sIAAAAAAAA/9LVVdDOzUwvSixJVQgt4HIOcnUMcVUIcXTycVXwdFPw8w9RcI3wDA4JVkjOSCwoSS0qVtDgUlBQUMhMUYCDMMcgZw/HIA0zE02wDr9QHx+FgCBPX8egSAVv10gdsI68xNxUdB2mBggdEFW5qSWJMFVewf5+MDaqqpzUxJTUoniwI7DZDjMrNwmsqhi7WVya1lxcyCHgkl+ex+US5B8ADQGYn625AAEAAP//UmeEQygBAAA=\"")
	packr.PackJSONBytes("./migrations", "2.sql", "\"H4sIAAAAAAAA/0yOQQuCQBBG7/MrvqNSQofq4mnTjSxTGdfIo5TEQpqo0d8Ptrac0xze+3ieh1mjb3011ig6ClgKJaHEJpaItkhSBXmOcpXjOdT9AIcAQF/xu5PgYCfYWS9dgydFHCPj6Ci4xEGWc2N0vW4vuqvuE2O1+BsfqqnHyu7u8zSxv6XI9YmmyeHj1VLIafZNNpE+vQMAAP//U0ET/9YAAAA=\"")
	packr.PackJSONBytes("./migrations", "3.sql", "\"H4sIAAAAAAAA/9LVVdDOzUwvSixJVQgt4HIOcnUMcVUIcXTycVXwdFPw8w9RcI3wDA4JVkgvzcxJKVbQ4FJQUFDITFGAgzDHIGcPxyANMxNNsHq/UB8fhYAgT1/HoEgFb9dIHbCOvMTcVHQdpgYIHRBVuakliTBVXsH+fjA2uqrcpNSi+MyUYuyquDStubiQfeaSX57H5RLkHwD1GcQv1lyAAAAA//+DzNy6/gAAAA==\"")
	packr.PackJSONBytes("./migrations", "4.sql", "\"H4sIAAAAAAAA/9LVVdDOzUwvSixJVQgt4HIOcnUMcVUIcXTycVXwdFPw8w9RcI3wDA4JViguLE1MKVbQ4FJQUFDITFHAAGGOQc4ejkEaZiaaYH1+oT4+CgFBnr6OQZEK3q6ROmCdeYm5qbh0mhogdEJU56aWJKKr9gr294OxUVUXFOWnlCaXxOeX56UWxUPciM1VMLNzk8DKivGbzaVpzcWFHE4u+eV5XC5B/gHQcIKEjDUXIAAA//936GrBTAEAAA==\"")
	packr.PackJSONBytes("./migrations", "5.sql", "\"H4sIAAAAAAAA/9LVVdDOzUwvSixJVQgt4HIOcnUMcVUIcXTycVXwdFPw8w9RcI3wDA4JVigpykxKLVbQ4FJQUFDITFGAgzDHIGcPxyANMxNNsHq/UB8fhYAgT1/HoEgFb9dIHbCOvMTcVHQdpgYIHRBVuakliTBVXsH+fjA2qqriwtLElPjMlGIcqrg0rbm4kH3mkl+ex+US5B8A9RnEL9ZcgAAAAP//0beY9v4AAAA=\"")
}
