// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"context"
	"crypto/tls"
	"github.com/google/wire"
	"github.com/grpc-ecosystem/go-grpc-middleware"
	"github.com/grpc-ecosystem/go-grpc-middleware/logging/zap"
	"github.com/grpc-ecosystem/go-grpc-middleware/recovery"
	"github.com/grpc-ecosystem/go-grpc-prometheus"
	"go.uber.org/zap"
	"go.zenithar.org/pkg/db/adapter/mongodb"
	"go.zenithar.org/pkg/db/adapter/postgresql"
	"go.zenithar.org/pkg/db/adapter/rethinkdb"
	"go.zenithar.org/pkg/log"
	"go.zenithar.org/pkg/tlsconfig"
	"go.zenithar.org/spotigraph/cmd/spotigraph/internal/config"
	mongodb2 "go.zenithar.org/spotigraph/internal/repositories/pkg/mongodb"
	postgresql2 "go.zenithar.org/spotigraph/internal/repositories/pkg/postgresql"
	rethinkdb2 "go.zenithar.org/spotigraph/internal/repositories/pkg/rethinkdb"
	"go.zenithar.org/spotigraph/internal/services"
	"go.zenithar.org/spotigraph/internal/services/pkg/chapter"
	"go.zenithar.org/spotigraph/internal/services/pkg/graph"
	"go.zenithar.org/spotigraph/internal/services/pkg/guild"
	"go.zenithar.org/spotigraph/internal/services/pkg/squad"
	"go.zenithar.org/spotigraph/internal/services/pkg/tribe"
	"go.zenithar.org/spotigraph/internal/services/pkg/user"
	"go.zenithar.org/spotigraph/pkg/grpc/v1/spotigraph/pb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/health"
	"google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/grpc/reflection"
	"strings"
)

// Injectors from injector.go:

func setupRethinkDB(ctx context.Context, cfg *config.Configuration) (*grpc.Server, error) {
	configuration := rdbConfig(cfg)
	session, err := rethinkdb.Connection(ctx, configuration)
	if err != nil {
		return nil, err
	}
	repositoriesUser := rethinkdb2.NewUserRepository(configuration, session)
	servicesUser := user.New(repositoriesUser)
	repositoriesChapter := rethinkdb2.NewChapterRepository(configuration, session)
	servicesChapter := chapter.New(repositoriesChapter)
	repositoriesGuild := rethinkdb2.NewGuildRepository(configuration, session)
	servicesGuild := guild.New(repositoriesGuild)
	repositoriesSquad := rethinkdb2.NewSquadRepository(configuration, session)
	servicesSquad := squad.New(repositoriesSquad)
	repositoriesTribe := rethinkdb2.NewTribeRepository(configuration, session)
	servicesTribe := tribe.New(repositoriesTribe)
	servicesGraph := graph.New(repositoriesUser, repositoriesSquad, repositoriesChapter, repositoriesGuild, repositoriesTribe)
	server, err := grpcServer(ctx, cfg, servicesUser, servicesChapter, servicesGuild, servicesSquad, servicesTribe, servicesGraph)
	if err != nil {
		return nil, err
	}
	return server, nil
}

func setupMongoDB(ctx context.Context, cfg *config.Configuration) (*grpc.Server, error) {
	configuration := mgoConfig(cfg)
	client, err := mongodb.Connection(ctx, configuration)
	if err != nil {
		return nil, err
	}
	repositoriesUser := mongodb2.NewUserRepository(configuration, client)
	servicesUser := user.New(repositoriesUser)
	repositoriesChapter := mongodb2.NewChapterRepository(configuration, client)
	servicesChapter := chapter.New(repositoriesChapter)
	repositoriesGuild := mongodb2.NewGuildRepository(configuration, client)
	servicesGuild := guild.New(repositoriesGuild)
	repositoriesSquad := mongodb2.NewSquadRepository(configuration, client)
	servicesSquad := squad.New(repositoriesSquad)
	repositoriesTribe := mongodb2.NewTribeRepository(configuration, client)
	servicesTribe := tribe.New(repositoriesTribe)
	servicesGraph := graph.New(repositoriesUser, repositoriesSquad, repositoriesChapter, repositoriesGuild, repositoriesTribe)
	server, err := grpcServer(ctx, cfg, servicesUser, servicesChapter, servicesGuild, servicesSquad, servicesTribe, servicesGraph)
	if err != nil {
		return nil, err
	}
	return server, nil
}

func setupPostgresDB(ctx context.Context, cfg *config.Configuration) (*grpc.Server, error) {
	configuration := pgConfig(cfg)
	db, err := postgresql.Connection(ctx, configuration)
	if err != nil {
		return nil, err
	}
	repositoriesUser := postgresql2.NewUserRepository(configuration, db)
	servicesUser := user.New(repositoriesUser)
	repositoriesChapter := postgresql2.NewChapterRepository(configuration, db)
	servicesChapter := chapter.New(repositoriesChapter)
	repositoriesGuild := postgresql2.NewGuildRepository(configuration, db)
	servicesGuild := guild.New(repositoriesGuild)
	repositoriesSquad := postgresql2.NewSquadRepository(configuration, db)
	servicesSquad := squad.New(repositoriesSquad)
	repositoriesTribe := postgresql2.NewTribeRepository(configuration, db)
	servicesTribe := tribe.New(repositoriesTribe)
	servicesGraph := graph.New(repositoriesUser, repositoriesSquad, repositoriesChapter, repositoriesGuild, repositoriesTribe)
	server, err := grpcServer(ctx, cfg, servicesUser, servicesChapter, servicesGuild, servicesSquad, servicesTribe, servicesGraph)
	if err != nil {
		return nil, err
	}
	return server, nil
}

// injector.go:

var serviceSet = wire.NewSet(user.New, chapter.New, squad.New, guild.New, tribe.New, graph.New)

// rdbConfig declares a Database configuration provider for Wire
func rdbConfig(cfg *config.Configuration) *rethinkdb.Configuration {
	return &rethinkdb.Configuration{
		AutoMigrate: cfg.Server.Database.AutoMigrate,
		Addresses:   strings.Split(cfg.Server.Database.Hosts, ","),
		Database:    cfg.Server.Database.Database,
		AuthKey:     cfg.Server.Database.Password,
	}
}

// mgoConfig declares a Database configuration provider for Wire
func mgoConfig(cfg *config.Configuration) *mongodb.Configuration {
	return &mongodb.Configuration{
		AutoMigrate:      cfg.Server.Database.AutoMigrate,
		ConnectionString: cfg.Server.Database.Hosts,
		DatabaseName:     cfg.Server.Database.Database,
		Username:         cfg.Server.Database.Username,
		Password:         cfg.Server.Database.Password,
	}
}

// pgConfig declares a Database configuration provider for Wire
func pgConfig(cfg *config.Configuration) *postgresql.Configuration {
	return &postgresql.Configuration{
		AutoMigrate:      cfg.Server.Database.AutoMigrate,
		ConnectionString: cfg.Server.Database.Hosts,
		Username:         cfg.Server.Database.Username,
		Password:         cfg.Server.Database.Password,
	}
}

func grpcServer(ctx context.Context, cfg *config.Configuration, users services.User, chapters services.Chapter, guilds services.Guild, squads services.Squad, tribes services.Tribe, graph2 services.Graph) (*grpc.Server, error) {

	sopts := []grpc.ServerOption{}
	grpc_zap.ReplaceGrpcLogger(zap.L())

	sopts = append(sopts, grpc.StreamInterceptor(grpc_middleware.ChainStreamServer(grpc_prometheus.StreamServerInterceptor, grpc_zap.StreamServerInterceptor(zap.L()), grpc_recovery.StreamServerInterceptor())), grpc.UnaryInterceptor(grpc_middleware.ChainUnaryServer(grpc_recovery.UnaryServerInterceptor(), grpc_prometheus.UnaryServerInterceptor, grpc_zap.UnaryServerInterceptor(zap.L()))))

	if cfg.Server.GRPC.UseTLS {

		clientAuth := tls.VerifyClientCertIfGiven
		if cfg.Server.GRPC.TLS.ClientAuthenticationRequired {
			clientAuth = tls.RequireAndVerifyClientCert
		}

		tlsConfig, err := tlsconfig.Server(tlsconfig.Options{
			KeyFile:    cfg.Server.GRPC.TLS.PrivateKeyPath,
			CertFile:   cfg.Server.GRPC.TLS.CertificatePath,
			CAFile:     cfg.Server.GRPC.TLS.CACertificatePath,
			ClientAuth: clientAuth,
		})
		if err != nil {
			log.For(ctx).Error("Unable to build TLS configuration from settings", zap.Error(err))
			return nil, err
		}

		sopts = append(sopts, grpc.Creds(credentials.NewTLS(tlsConfig)))
	} else {
		log.For(ctx).Info("No transport authentication enabled")
	}

	server := grpc.NewServer(sopts...)

	healthServer := health.NewServer()
	grpc_health_v1.RegisterHealthServer(server, healthServer)
	pb.RegisterUserServer(server, users)
	pb.RegisterChapterServer(server, chapters)
	pb.RegisterGuildServer(server, guilds)
	pb.RegisterSquadServer(server, squads)
	pb.RegisterTribeServer(server, tribes)
	pb.RegisterGraphServer(server, graph2)
	reflection.Register(server)

	return server, nil
}
